#!/usr/bin/env node

/**
 * Dependencies
 */

var p = require('commander'),
	commands = require('./commands');

var conf = require('./configure');

if (p.configure) {
	module.exports = conf;
}

p.version('0.0.1').usage('This is default stuff').option('-v, --verbose [value]', 'display all logs');

conf.propsLoaded(function() {
	console.log('test');
	p.command('run')
	 .description('Run a project on simulator/emulator')
	 .option('-p, --platform <platform>','the platform to target, one of "iphone", "ipad", "android"')
	 .option('-d, --directory [directory]','the project directory to use, default to current directory')
	 .action(require('./command_run').execute);
	 p.parse(process.argv);
});
